### ISSUE TITLE
Create a server / client architecture

### ISSUE THREAD

**Issue by pscott** [pscott/TaskMaster#7]
This is a useful bonus for the taskmaster project.

I think we could use the [daemonize](https://docs.rs/daemonize/0.4.1/daemonize/) crate for that purpose :)

**Comment by Ant0wan** [comment]
Yep

**Comment by pscott** [comment]
Reopening because we [reverted](https://github.com/pscott/TaskMaster/commit/3988fd7562ade843f2eaf446d18bd36cf704e156) the PR.

**Comment by pscott** [comment]
Closed by #11

**Comment by Ant0wan** [comment]
I will push to add daemonize function to taskmasterd.

**Comment by pscott** [comment]
> I will push to add daemonize function to taskmasterd.

I don't think we need it. It works pretty well right now without using any other crate. Any particular reason you want to use daemonize?

**Comment by Ant0wan** [comment]
In our case we are not daemonizing the process. We keep hanging the tty and we are bound to the user SID.
In order for it to be a proper daemon, we need:
- to call umask to change it for 027 or 077 depending on what we want to achieve,
- to fork the process and exit parent to garantee process is not seesion leader and it is a prerequiste for calling setsid
- to call setsid to create new session -> mmakes it process leader of new session and process group and is disassociated from its controlling terminal
- it changes working directory of process
- it closes unneeded file descriptors
- dup fds to log file 
daemonize() allows taskmasterd to do so.
I think it is important. What do you think ?

**Comment by pscott** [comment]
@Ant0wan You're right, this would bring in bonus points (and would make it a lot cleaner). Thanks for explaining! :D Will review the PR ASAP :)
